name: Deploy Hugo site via GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.127.0"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Debug - List public directory
        run: ls -R public

      - name: Debug - Check for Mermaid script
        run: grep -R "mermaid.min.js" public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public